version: '3'
services:
    nginx:
        image: nginx:1.14
        restart: unless-stopped
        volumes:
            - ./:/var/docker

            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./.docker/nginx/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf:ro
            - ./.docker/nginx/server.conf:/etc/nginx/conf.d/server.conf:ro
        networks:
            cookbook:
                ipv4_address: ${NGINX_IPV4:-172.22.0.20}

    php:
        build: ./.docker/php
        restart: unless-stopped
        volumes:
            - ./:/var/docker
        networks:
            - cookbook
        env_file:
            - .env.defaults
            - .env.local

    mariadb:
        image: mariadb:10.4.12
        restart: unless-stopped
        volumes:
            - mariadb-data:/var/lib/mysql
        networks:
            - cookbook
        env_file:
            - .env.defaults
            - .env.local

    rabbit:
        build: ./.docker/rabbit
        restart: unless-stopped
        networks:
            - cookbook
        env_file:
            - .env.defaults
            - .env.local

volumes:
    mariadb-data:

networks:
    cookbook:
        ipam:
            driver: default
            config:
                - subnet: ${SUBNET:-172.22.0.0}/24



